on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ 
        github.ref_name == 'prod' && 'production' || 
        github.ref_name == 'qa' && 'qa' || 
        'develop' 
        }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set database connection string
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: |
          echo "Database URL is $DATABASE_URL of ${GITHUB_ENV}""
# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: sampathbank-mit/frontend-test-image # Convert to lowercase

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '16'

#       - name: Install dependencies
#         run: npm install

#       - name: Run tests
#         run: echo "npm test"

#   build-and-push:
#     runs-on: ubuntu-latest
#     needs: test
#     steps:
#       - uses: actions/checkout@v2

#       # Set up Docker
#       - name: Log in to GitHub Docker Registry
#         run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

#       # Build the Docker image (with lowercase repository name)
#       - name: Build Docker image
#         run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .

#       # Push the Docker image to GitHub Packages
#       - name: Push Docker image to GitHub Packages
#         run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
